server:
  port: 7002
  error:
    include-message: always

spring.redis:
  host: localhost
  port: 6379
  database: 0
  password: pwd

logging:
  level:
    root: INFO
    com.habeebcycle: DEBUG
    org.springframework.data.redis: DEBUG

---
spring:
  config:
    activate:
      on-profile:
        - docker
  redis.host: redis

server:
  port: 8080